### ISSUE TITLE
use of environment variables in yml

### ISSUE THREAD

**Issue by emmanuelgomez** [MattRoss34/spring-cloud-config#61]
I cannot use environment variables in the yml of the form zzz: $ {yyy: http: // localhost}

**Comment by MattRoss34** [comment]
You can pass in your env variables directly, like:
```
zzz=yyy node server.js
```

The env variables passed in like above will be merged with your yaml config.  So for example if you have a DB username and password, you can keep your username in your config, but pass in the password via env variable, like so:

**application.yml**
```
spring.cloud.config.name: my-application-name
db:
   mongo:
      url: http://localhost:27017
      username: someuser
```

**Pass in the ENV variables**
```
db.mongo.password=mypass node server.js
```

**Then use the config in your code**
```javascript
const SpringCloudConfig = require('spring-cloud-config');

const myConfig = SpringCloudConfig.instance();

const url = `mongodb://${myConfig.db.mongo.username}:${myConfig.db.mongo.password}@${myConfig.db.mongo.url}`;
```
